services:
  db:
    image: postgres:14-alpine
    container_name: tf_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tfdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer
    container_name: tf_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tf_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://root:password@db:5432/tfdb?sslmode=disable
      PORT: 8000
    depends_on:
      - db
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
